### ISSUE TITLE
El Capitan Installation i3 version

### ISSUE THREAD

**Issue by Alexusz2000** [Kaijun/Acer-V5-573G-Hackintosh#37]
How?

**Comment by Silveryard** [comment]
As Described in Issue #7 
The steps are the same. Just make sure you have the newest bios version (i think 2.30+ is okay) and select the files from the appropriate branch depending on your hardware specs

**Comment by Alexusz2000** [comment]
i3 version ok?

**Comment by Silveryard** [comment]
Theres an i3 version of the 573? Then you might want to use the file from master. i5 and i7 branches contain a few fixes for  El Capitan but you may need to edit some configs to work for your i3

**Comment by Alexusz2000** [comment]
Here: http://specsen.com/laptops-acer/acer-aspire-v5-573g-34014g50a-core-i3-4010u-1700-mhz-15-6-1366x768-4gb-500gb-dvd-none-nvidia-geforce-gt-720m-wi-fi-bluetooth-linux-/

How edit configs? I'm starting... :(

**Comment by Kaijun** [comment]
first of all, you should have some basic knowledges of hackintosh... 
this repository is only for people who want to achieve more compatible v5-573g and explore how to make all stuffs work. 

So basically you should know how a general installation process is,  and then reference the issues/tutorial for our specific model.
and you should also know what DSDT, SSDT means, 

for your own i3 version, you may also manage to generating an specific SSDT for your i3 cpu in order to make speedstepping work.

**Comment by Alexusz2000** [comment]
Thanks for your help :) I can not solve i3 compatible :S

**Comment by Kaijun** [comment]
Use all files in this Repo and follow the tutorial #7 

Reopen if you still have difficulties
